2025-03-03 10:03:39,176 - INFO - hlo
2025-03-03 10:03:39,178 - INFO - Starting consumer... Waiting 5 seconds to ensure RabbitMQ is ready.
2025-03-03 10:03:44,184 - INFO - Connecting to RabbitMQ...
2025-03-03 10:03:44,194 - INFO - Pika version 1.3.2 connecting to ('172.18.0.3', 5672)
2025-03-03 10:03:44,195 - INFO - Socket connected: <socket.socket fd=7, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('172.18.0.8', 58784), raddr=('172.18.0.3', 5672)>
2025-03-03 10:03:44,197 - INFO - Streaming transport linked up: (<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f151cff41f0>, _StreamingProtocolShim: <SelectConnection PROTOCOL transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f151cff41f0> params=<ConnectionParameters host=rabbitmq port=5672 virtual_host=/ ssl=False>>).
2025-03-03 10:03:44,230 - INFO - AMQPConnector - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f151cff41f0> params=<ConnectionParameters host=rabbitmq port=5672 virtual_host=/ ssl=False>>
2025-03-03 10:03:44,232 - INFO - AMQPConnectionWorkflow - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f151cff41f0> params=<ConnectionParameters host=rabbitmq port=5672 virtual_host=/ ssl=False>>
2025-03-03 10:03:44,234 - INFO - Connection workflow succeeded: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f151cff41f0> params=<ConnectionParameters host=rabbitmq port=5672 virtual_host=/ ssl=False>>
2025-03-03 10:03:44,238 - INFO - Connected to RabbitMQ successfully.
2025-03-03 10:03:44,247 - INFO - Created channel=1
2025-03-03 10:03:44,266 - INFO -  [✔] Waiting for messages from Appointment Service...
2025-03-03 10:06:49,678 - INFO - Aborting transport connection: state=1; <socket.socket fd=7, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('172.18.0.8', 58784)>
2025-03-03 10:06:49,696 - INFO - _AsyncTransportBase._initate_abort(): Initiating abrupt asynchronous transport shutdown: state=1; error=None; <socket.socket fd=7, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('172.18.0.8', 58784)>
2025-03-03 10:06:49,714 - INFO - Deactivating transport: state=1; <socket.socket fd=7, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('172.18.0.8', 58784)>
2025-03-03 10:06:49,733 - INFO - AMQP stack terminated, failed to connect, or aborted: opened=True, error-arg=None; pending-error=ConnectionClosedByBroker: (320) "CONNECTION_FORCED - broker forced connection closure with reason 'shutdown'"
2025-03-03 10:06:49,752 - INFO - Stack terminated due to ConnectionClosedByBroker: (320) "CONNECTION_FORCED - broker forced connection closure with reason 'shutdown'"
2025-03-03 10:06:49,770 - INFO - Closing transport socket and unlinking: state=3; <socket.socket fd=7, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('172.18.0.8', 58784)>
2025-03-03 10:06:49,803 - ERROR - Unexpected connection close detected: ConnectionClosedByBroker: (320) "CONNECTION_FORCED - broker forced connection closure with reason 'shutdown'"
2025-03-03 10:06:49,820 - ERROR - RabbitMQ connection lost: (320, "CONNECTION_FORCED - broker forced connection closure with reason 'shutdown'"). Reconnecting in 5 seconds...
2025-03-03 10:06:54,828 - INFO - Connecting to RabbitMQ...
2025-03-03 10:06:58,217 - ERROR - Address resolution failed: gaierror(-2, 'Name or service not known')
2025-03-03 10:06:58,220 - ERROR - getaddrinfo failed: gaierror(-2, 'Name or service not known').
2025-03-03 10:06:58,221 - ERROR - AMQP connection workflow failed: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - gaierror(-2, 'Name or service not known'); first exception - None.
2025-03-03 10:06:58,226 - ERROR - AMQPConnectionWorkflow - reporting failure: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - gaierror(-2, 'Name or service not known'); first exception - None
2025-03-03 10:06:58,229 - ERROR - Connection workflow failed: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - gaierror(-2, 'Name or service not known'); first exception - None
2025-03-03 10:06:58,234 - ERROR - Error in _create_connection().
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/pika/adapters/blocking_connection.py", line 451, in _create_connection
    raise self._reap_last_connection_workflow_error(error)
  File "/usr/local/lib/python3.10/site-packages/pika/adapters/utils/selector_ioloop_adapter.py", line 565, in _resolve
    result = socket.getaddrinfo(self._host, self._port, self._family,
  File "/usr/local/lib/python3.10/socket.py", line 967, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known
2025-03-03 10:06:58,239 - ERROR - Consumer error: [Errno -2] Name or service not known. Restarting in 5 seconds...
2025-03-03 10:10:20,652 - INFO - hlo
2025-03-03 10:10:21,060 - INFO - Starting consumer... Waiting 5 seconds to ensure RabbitMQ is ready.
2025-03-03 10:10:26,072 - INFO - Connecting to RabbitMQ...
2025-03-03 10:10:26,155 - INFO - Pika version 1.3.2 connecting to ('172.18.0.3', 5672)
2025-03-03 10:10:26,172 - INFO - Socket connected: <socket.socket fd=7, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('172.18.0.6', 55286), raddr=('172.18.0.3', 5672)>
2025-03-03 10:10:26,187 - INFO - Streaming transport linked up: (<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f5b54bf81f0>, _StreamingProtocolShim: <SelectConnection PROTOCOL transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f5b54bf81f0> params=<ConnectionParameters host=rabbitmq port=5672 virtual_host=/ ssl=False>>).
2025-03-03 10:10:26,256 - INFO - AMQPConnector - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f5b54bf81f0> params=<ConnectionParameters host=rabbitmq port=5672 virtual_host=/ ssl=False>>
2025-03-03 10:10:26,268 - INFO - AMQPConnectionWorkflow - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f5b54bf81f0> params=<ConnectionParameters host=rabbitmq port=5672 virtual_host=/ ssl=False>>
2025-03-03 10:10:26,380 - INFO - Connection workflow succeeded: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f5b54bf81f0> params=<ConnectionParameters host=rabbitmq port=5672 virtual_host=/ ssl=False>>
2025-03-03 10:10:26,397 - INFO - Connected to RabbitMQ successfully.
2025-03-03 10:10:26,412 - INFO - Created channel=1
2025-03-03 10:10:26,433 - INFO -  [✔] Waiting for messages from Appointment Service...
2025-03-03 10:14:02,838 - INFO - Aborting transport connection: state=1; <socket.socket fd=7, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('172.18.0.6', 55286)>
2025-03-03 10:14:02,938 - INFO - _AsyncTransportBase._initate_abort(): Initiating abrupt asynchronous transport shutdown: state=1; error=None; <socket.socket fd=7, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('172.18.0.6', 55286)>
2025-03-03 10:14:02,970 - INFO - Deactivating transport: state=1; <socket.socket fd=7, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('172.18.0.6', 55286)>
2025-03-03 10:14:02,987 - INFO - AMQP stack terminated, failed to connect, or aborted: opened=True, error-arg=None; pending-error=ConnectionClosedByBroker: (320) "CONNECTION_FORCED - broker forced connection closure with reason 'shutdown'"
2025-03-03 10:14:03,003 - INFO - Stack terminated due to ConnectionClosedByBroker: (320) "CONNECTION_FORCED - broker forced connection closure with reason 'shutdown'"
2025-03-03 10:14:03,117 - INFO - Closing transport socket and unlinking: state=3; <socket.socket fd=7, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('172.18.0.6', 55286)>
2025-03-03 10:14:03,135 - ERROR - Unexpected connection close detected: ConnectionClosedByBroker: (320) "CONNECTION_FORCED - broker forced connection closure with reason 'shutdown'"
2025-03-03 10:14:03,199 - ERROR - RabbitMQ connection lost: (320, "CONNECTION_FORCED - broker forced connection closure with reason 'shutdown'"). Reconnecting in 5 seconds...
2025-03-03 10:14:08,247 - INFO - Connecting to RabbitMQ...
2025-03-03 10:15:53,143 - INFO - hlo
2025-03-03 10:15:53,146 - INFO - Starting consumer... Waiting 5 seconds to ensure RabbitMQ is ready.
2025-03-03 10:15:58,151 - INFO - Connecting to RabbitMQ...
2025-03-03 10:15:58,164 - INFO - Pika version 1.3.2 connecting to ('172.18.0.3', 5672)
2025-03-03 10:15:58,165 - ERROR - Socket failed to connect: <socket.socket fd=7, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('172.18.0.7', 38926)>; error=111 (Connection refused)
2025-03-03 10:15:58,167 - ERROR - TCP Connection attempt failed: ConnectionRefusedError(111, 'Connection refused'); dest=(<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('172.18.0.3', 5672))
2025-03-03 10:15:58,170 - ERROR - AMQPConnector - reporting failure: AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused')
2025-03-03 10:15:58,173 - ERROR - AMQP connection workflow failed: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused'); first exception - None.
2025-03-03 10:15:58,176 - ERROR - AMQPConnectionWorkflow - reporting failure: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused'); first exception - None
2025-03-03 10:15:58,178 - ERROR - Connection workflow failed: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused'); first exception - None
2025-03-03 10:15:58,188 - ERROR - Error in _create_connection().
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/pika/adapters/blocking_connection.py", line 451, in _create_connection
    raise self._reap_last_connection_workflow_error(error)
pika.exceptions.AMQPConnectionError
2025-03-03 10:15:58,191 - WARNING - Retry 1/15 - Waiting for RabbitMQ...
2025-03-03 10:16:03,200 - INFO - Pika version 1.3.2 connecting to ('172.18.0.3', 5672)
2025-03-03 10:16:03,204 - ERROR - Socket failed to connect: <socket.socket fd=7, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('172.18.0.7', 38940)>; error=111 (Connection refused)
2025-03-03 10:16:03,211 - ERROR - TCP Connection attempt failed: ConnectionRefusedError(111, 'Connection refused'); dest=(<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('172.18.0.3', 5672))
2025-03-03 10:16:03,226 - ERROR - AMQPConnector - reporting failure: AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused')
2025-03-03 10:16:03,232 - ERROR - AMQP connection workflow failed: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused'); first exception - None.
2025-03-03 10:16:03,235 - ERROR - AMQPConnectionWorkflow - reporting failure: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused'); first exception - None
2025-03-03 10:16:03,242 - ERROR - Connection workflow failed: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused'); first exception - None
2025-03-03 10:16:03,247 - ERROR - Error in _create_connection().
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/pika/adapters/blocking_connection.py", line 451, in _create_connection
    raise self._reap_last_connection_workflow_error(error)
pika.exceptions.AMQPConnectionError
2025-03-03 10:16:03,249 - WARNING - Retry 2/15 - Waiting for RabbitMQ...
2025-03-03 10:16:08,261 - INFO - Pika version 1.3.2 connecting to ('172.18.0.3', 5672)
2025-03-03 10:16:08,263 - INFO - Socket connected: <socket.socket fd=7, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('172.18.0.7', 43074), raddr=('172.18.0.3', 5672)>
2025-03-03 10:16:08,266 - INFO - Streaming transport linked up: (<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f48aebca740>, _StreamingProtocolShim: <SelectConnection PROTOCOL transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f48aebca740> params=<ConnectionParameters host=rabbitmq port=5672 virtual_host=/ ssl=False>>).
2025-03-03 10:16:09,059 - INFO - AMQPConnector - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f48aebca740> params=<ConnectionParameters host=rabbitmq port=5672 virtual_host=/ ssl=False>>
2025-03-03 10:16:09,063 - INFO - AMQPConnectionWorkflow - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f48aebca740> params=<ConnectionParameters host=rabbitmq port=5672 virtual_host=/ ssl=False>>
2025-03-03 10:16:09,067 - INFO - Connection workflow succeeded: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f48aebca740> params=<ConnectionParameters host=rabbitmq port=5672 virtual_host=/ ssl=False>>
2025-03-03 10:16:09,070 - INFO - Connected to RabbitMQ successfully.
2025-03-03 10:16:09,080 - INFO - Created channel=1
2025-03-03 10:16:09,095 - INFO -  [✔] Waiting for messages from Appointment Service...
